"""New Migration

Revision ID: baa9097006be
Revises: 
Create Date: 2023-01-01 18:24:48.148114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa9097006be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
       sa.Column('id', sa.UUID(as_uuid=True), primary_key=True),
        sa.Column('type', sa.Enum('lost', 'found', name='itemtype'), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('location_lat', sa.String(), nullable=False),
        sa.Column('location_lng', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('status', sa.Enum('open', 'resolved', name='itemstatus'), nullable=False, server_default='open'),
        sa.Column('contact_email', sa.String(), nullable=False),
        sa.Column('contact_name', sa.String(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=True),
    )
    op.create_table(
        'matches',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True),
        sa.Column('item_id', sa.UUID(as_uuid=True), sa.ForeignKey('items.id'), nullable=False),
        sa.Column('matched_item_id', sa.UUID(as_uuid=True), sa.ForeignKey('items.id'), nullable=False),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('matched_on', sa.DateTime(timezone=True), server_default=sa.func.now())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('items')
    op.drop_table
    # ### end Alembic commands ###
